kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: {{.Values.treePVC.name }}
  name: {{ .Values.treePVC.name }}
spec:
  accessModes:
    - {{ .Values.treePVC.accessmode | quote }}
  resources:
    requests:
      storage: {{ .Values.treePVC.size | quote }}
  storageClassName: {{ .Values.treePVC.storage | quote }}
